databases:
  - name: YUKI KUDO
    databaseName: nr6_server_manage_app_production
    user: nr6_server_manage_app
    region: singapore

services:
  - type: web
    name: nrx-web-app
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: YUKI KUDO
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
